id: P1F55B2DA
initial_creation_type: input
source_metadata:
  title: Tilopa
  language: bo
  description: 'Texts by and about the great siddha Tilopa (ti lo pa, 988–1069):'
  volume:
    180df3662c86454393daef17d968ead0:
      title: The Ganges Mahāmudrā Instructions
      parent: Advice
created_at: '2022-03-01T02:25:12.716485'
last_modified_at: '2022-03-01T02:25:12.716488'
statistics:
  total_words: 1004
  total_non_words: 111
quality:
  non_words_ratio: 0.11
